language: csharp
solution: FossilDelta.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
install:
  - nuget restore FossilDelta.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release FossilDelta.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/bin/Release/Tests.dll
