//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace System.Text.Json
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Text.Json.src.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The maximum configured depth of {0} has been exceeded. Cannot read next JSON array..
        /// </summary>
        public static string ArrayDepthTooLarge
        {
            get
            {
                return ResourceManager.GetString("ArrayDepthTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON array was modified during iteration..
        /// </summary>
        public static string ArrayModifiedDuringIteration
        {
            get
            {
                return ResourceManager.GetString("ArrayModifiedDuringIteration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot allocate a buffer of size {0}..
        /// </summary>
        public static string BufferMaximumSizeExceeded
        {
            get
            {
                return ResourceManager.GetString("BufferMaximumSizeExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot advance past the end of the buffer, which has a size of {0}..
        /// </summary>
        public static string BufferWriterAdvancedTooFar
        {
            get
            {
                return ResourceManager.GetString("BufferWriterAdvancedTooFar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON writer needs to be flushed before getting the current state. There are {0} bytes that have not been committed to the output..
        /// </summary>
        public static string CallFlushToAvoidDataLoss
        {
            get
            {
                return ResourceManager.GetString("CallFlushToAvoidDataLoss", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot decode JSON text that is not encoded as valid Base64 to bytes..
        /// </summary>
        public static string CannotDecodeInvalidBase64
        {
            get
            {
                return ResourceManager.GetString("CannotDecodeInvalidBase64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot encode invalid UTF-16 text as JSON. Invalid surrogate value: &apos;{0}&apos;..
        /// </summary>
        public static string CannotEncodeInvalidUTF16
        {
            get
            {
                return ResourceManager.GetString("CannotEncodeInvalidUTF16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot encode invalid UTF-8 text as JSON. Invalid input: &apos;{0}&apos;..
        /// </summary>
        public static string CannotEncodeInvalidUTF8
        {
            get
            {
                return ResourceManager.GetString("CannotEncodeInvalidUTF8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The collection type &apos;{0}&apos; is abstract, an interface, or is read only, and could not be instantiated and populated..
        /// </summary>
        public static string CannotPopulateCollection
        {
            get
            {
                return ResourceManager.GetString("CannotPopulateCollection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot read incomplete UTF-16 JSON text as string with missing low surrogate..
        /// </summary>
        public static string CannotReadIncompleteUTF16
        {
            get
            {
                return ResourceManager.GetString("CannotReadIncompleteUTF16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot read invalid UTF-16 JSON text as string. Invalid surrogate value: &apos;{0}&apos;..
        /// </summary>
        public static string CannotReadInvalidUTF16
        {
            get
            {
                return ResourceManager.GetString("CannotReadInvalidUTF16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of property &apos;{1}&apos; on type &apos;{2}&apos; is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types..
        /// </summary>
        public static string CannotSerializeInvalidMember
        {
            get
            {
                return ResourceManager.GetString("CannotSerializeInvalidMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types..
        /// </summary>
        public static string CannotSerializeInvalidType
        {
            get
            {
                return ResourceManager.GetString("CannotSerializeInvalidType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot skip tokens on partial JSON. Either get the whole payload and create a Utf8JsonReader instance where isFinalBlock is true or call TrySkip..
        /// </summary>
        public static string CannotSkip
        {
            get
            {
                return ResourceManager.GetString("CannotSkip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write the start of an object/array after a single JSON value or outside of an existing closed object/array. Current token type is &apos;{0}&apos;..
        /// </summary>
        public static string CannotStartObjectArrayAfterPrimitiveOrClose
        {
            get
            {
                return ResourceManager.GetString("CannotStartObjectArrayAfterPrimitiveOrClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write the start of an object or array without a property name. Current token type is &apos;{0}&apos;..
        /// </summary>
        public static string CannotStartObjectArrayWithoutProperty
        {
            get
            {
                return ResourceManager.GetString("CannotStartObjectArrayWithoutProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot transcode invalid UTF-16 string to UTF-8 JSON text..
        /// </summary>
        public static string CannotTranscodeInvalidUtf16
        {
            get
            {
                return ResourceManager.GetString("CannotTranscodeInvalidUtf16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot transcode invalid UTF-8 JSON text to UTF-16 string..
        /// </summary>
        public static string CannotTranscodeInvalidUtf8
        {
            get
            {
                return ResourceManager.GetString("CannotTranscodeInvalidUtf8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write a comment value which contains the end of comment delimiter..
        /// </summary>
        public static string CannotWriteCommentWithEmbeddedDelimiter
        {
            get
            {
                return ResourceManager.GetString("CannotWriteCommentWithEmbeddedDelimiter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid following a property name..
        /// </summary>
        public static string CannotWriteEndAfterProperty
        {
            get
            {
                return ResourceManager.GetString("CannotWriteEndAfterProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write a JSON property name following another property name. A JSON value is missing..
        /// </summary>
        public static string CannotWritePropertyAfterProperty
        {
            get
            {
                return ResourceManager.GetString("CannotWritePropertyAfterProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write a JSON property within an array or as the first JSON token. Current token type is &apos;{0}&apos;..
        /// </summary>
        public static string CannotWritePropertyWithinArray
        {
            get
            {
                return ResourceManager.GetString("CannotWritePropertyWithinArray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write a JSON value after a single JSON value or outside of an existing closed object/array. Current token type is &apos;{0}&apos;..
        /// </summary>
        public static string CannotWriteValueAfterPrimitiveOrClose
        {
            get
            {
                return ResourceManager.GetString("CannotWriteValueAfterPrimitiveOrClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write a JSON value within an object without a property name. Current token type is &apos;{0}&apos;..
        /// </summary>
        public static string CannotWriteValueWithinObject
        {
            get
            {
                return ResourceManager.GetString("CannotWriteValueWithinObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JsonCommentHandling enum must be set to one of the supported values..
        /// </summary>
        public static string CommentHandlingMustBeValid
        {
            get
            {
                return ResourceManager.GetString("CommentHandlingMustBeValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The constructor &apos;{0}&apos; on type &apos;{1}&apos; may not have more than 64 parameters for deserialization..
        /// </summary>
        public static string ConstructorMaxOf64Parameters
        {
            get
            {
                return ResourceManager.GetString("ConstructorMaxOf64Parameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Each parameter in constructor &apos;{0}&apos; on type &apos;{1}&apos; must bind to an object member on deserialization. Each parameter name must be the camel case equivalent of an object member named with the pascal case naming convention..
        /// </summary>
        public static string ConstructorParamIncompleteBinding
        {
            get
            {
                return ResourceManager.GetString("ConstructorParamIncompleteBinding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;IgnoreNullValues&apos; and &apos;DefaultIgnoreCondition&apos; cannot both be set to non-default values..
        /// </summary>
        public static string DefaultIgnoreConditionAlreadySpecified
        {
            get
            {
                return ResourceManager.GetString("DefaultIgnoreConditionAlreadySpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value cannot be &apos;JsonIgnoreCondition.Always&apos;..
        /// </summary>
        public static string DefaultIgnoreConditionInvalid
        {
            get
            {
                return ResourceManager.GetString("DefaultIgnoreConditionInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CurrentDepth ({0}) is equal to or larger than the maximum allowed depth of {1}. Cannot write the next JSON object or array..
        /// </summary>
        public static string DepthTooLarge
        {
            get
            {
                return ResourceManager.GetString("DepthTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An item with the same property name &apos;{0}&apos; has already been added..
        /// </summary>
        public static string DeserializeDuplicateKey
        {
            get
            {
                return ResourceManager.GetString("DeserializeDuplicateKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with &apos;{0}&apos; is not supported. Type &apos;{1}&apos;..
        /// </summary>
        public static string DeserializeNoConstructor
        {
            get
            {
                return ResourceManager.GetString("DeserializeNoConstructor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deserialization of interface types is not supported. Type &apos;{0}&apos;..
        /// </summary>
        public static string DeserializePolymorphicInterface
        {
            get
            {
                return ResourceManager.GetString("DeserializePolymorphicInterface", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON value could not be converted to {0}..
        /// </summary>
        public static string DeserializeUnableToConvertValue
        {
            get
            {
                return ResourceManager.GetString("DeserializeUnableToConvertValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified type {0} must derive from the specific value&apos;s type {1}..
        /// </summary>
        public static string DeserializeWrongType
        {
            get
            {
                return ResourceManager.GetString("DeserializeWrongType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a supported Dictionary key type..
        /// </summary>
        public static string DictionaryKeyTypeNotSupported
        {
            get
            {
                return ResourceManager.GetString("DictionaryKeyTypeNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Writing an empty JSON payload (excluding comments) is invalid..
        /// </summary>
        public static string EmptyJsonIsInvalid
        {
            get
            {
                return ResourceManager.GetString("EmptyJsonIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a number, but instead got empty string..
        /// </summary>
        public static string EmptyStringToInitializeNumber
        {
            get
            {
                return ResourceManager.GetString("EmptyStringToInitializeNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected end of comment, but instead reached end of data..
        /// </summary>
        public static string EndOfCommentNotFound
        {
            get
            {
                return ResourceManager.GetString("EndOfCommentNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected end of string, but instead reached end of data..
        /// </summary>
        public static string EndOfStringNotFound
        {
            get
            {
                return ResourceManager.GetString("EndOfStringNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid after a single JSON value. Expected end of data..
        /// </summary>
        public static string ExpectedEndAfterSingleJson
        {
            get
            {
                return ResourceManager.GetString("ExpectedEndAfterSingleJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid end of a number. Expected a delimiter..
        /// </summary>
        public static string ExpectedEndOfDigitNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpectedEndOfDigitNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid JSON literal. Expected the literal &apos;false&apos;..
        /// </summary>
        public static string ExpectedFalse
        {
            get
            {
                return ResourceManager.GetString("ExpectedFalse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true..
        /// </summary>
        public static string ExpectedJsonTokens
        {
            get
            {
                return ResourceManager.GetString("ExpectedJsonTokens", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid end of a number. Expected &apos;E&apos; or &apos;e&apos;..
        /// </summary>
        public static string ExpectedNextDigitEValueNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpectedNextDigitEValueNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid JSON literal. Expected the literal &apos;null&apos;..
        /// </summary>
        public static string ExpectedNull
        {
            get
            {
                return ResourceManager.GetString("ExpectedNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The input does not contain any complete JSON tokens. Expected the input to have at least one valid, complete, JSON token..
        /// </summary>
        public static string ExpectedOneCompleteToken
        {
            get
            {
                return ResourceManager.GetString("ExpectedOneCompleteToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid after a property name. Expected a &apos;:&apos;..
        /// </summary>
        public static string ExpectedSeparatorAfterPropertyNameNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpectedSeparatorAfterPropertyNameNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid start of a property name. Expected a &apos;&quot;&apos;..
        /// </summary>
        public static string ExpectedStartOfPropertyNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpectedStartOfPropertyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid start of a property name or value, after a comment..
        /// </summary>
        public static string ExpectedStartOfPropertyOrValueAfterComment
        {
            get
            {
                return ResourceManager.GetString("ExpectedStartOfPropertyOrValueAfterComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected start of a property name or value, but instead reached end of data..
        /// </summary>
        public static string ExpectedStartOfPropertyOrValueNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpectedStartOfPropertyOrValueNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid start of a value..
        /// </summary>
        public static string ExpectedStartOfValueNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpectedStartOfValueNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid JSON literal. Expected the literal &apos;true&apos;..
        /// </summary>
        public static string ExpectedTrue
        {
            get
            {
                return ResourceManager.GetString("ExpectedTrue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a value, but instead reached end of data..
        /// </summary>
        public static string ExpectedValueAfterPropertyNameNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpectedValueAfterPropertyNameNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The extension data property &apos;{0}&apos; on type &apos;{1}&apos; cannot bind with a parameter in constructor &apos;{2}&apos;..
        /// </summary>
        public static string ExtensionDataCannotBindToCtorParam
        {
            get
            {
                return ResourceManager.GetString("ExtensionDataCannotBindToCtorParam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;IBufferWriter&apos; could not provide an output buffer that is large enough to continue writing..
        /// </summary>
        public static string FailedToGetLargerSpan
        {
            get
            {
                return ResourceManager.GetString("FailedToGetLargerSpan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON value is not in a supported Boolean format..
        /// </summary>
        public static string FormatBoolean
        {
            get
            {
                return ResourceManager.GetString("FormatBoolean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for an unsigned byte..
        /// </summary>
        public static string FormatByte
        {
            get
            {
                return ResourceManager.GetString("FormatByte", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON value is not in a supported DateTime format..
        /// </summary>
        public static string FormatDateTime
        {
            get
            {
                return ResourceManager.GetString("FormatDateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON value is not in a supported DateTimeOffset format..
        /// </summary>
        public static string FormatDateTimeOffset
        {
            get
            {
                return ResourceManager.GetString("FormatDateTimeOffset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON value is either too large or too small for a Decimal..
        /// </summary>
        public static string FormatDecimal
        {
            get
            {
                return ResourceManager.GetString("FormatDecimal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for a Double..
        /// </summary>
        public static string FormatDouble
        {
            get
            {
                return ResourceManager.GetString("FormatDouble", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON value is not in a supported Guid format..
        /// </summary>
        public static string FormatGuid
        {
            get
            {
                return ResourceManager.GetString("FormatGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for an Int16..
        /// </summary>
        public static string FormatInt16
        {
            get
            {
                return ResourceManager.GetString("FormatInt16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for an Int32..
        /// </summary>
        public static string FormatInt32
        {
            get
            {
                return ResourceManager.GetString("FormatInt32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for an Int64..
        /// </summary>
        public static string FormatInt64
        {
            get
            {
                return ResourceManager.GetString("FormatInt64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for a signed byte..
        /// </summary>
        public static string FormatSByte
        {
            get
            {
                return ResourceManager.GetString("FormatSByte", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for a Single..
        /// </summary>
        public static string FormatSingle
        {
            get
            {
                return ResourceManager.GetString("FormatSingle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for a UInt16..
        /// </summary>
        public static string FormatUInt16
        {
            get
            {
                return ResourceManager.GetString("FormatUInt16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for a UInt32..
        /// </summary>
        public static string FormatUInt32
        {
            get
            {
                return ResourceManager.GetString("FormatUInt32", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either the JSON value is not in a supported format, or is out of bounds for a UInt64..
        /// </summary>
        public static string FormatUInt64
        {
            get
            {
                return ResourceManager.GetString("FormatUInt64", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid after a value. Expected either &apos;,&apos;, &apos;}}&apos;, or &apos;]&apos;..
        /// </summary>
        public static string FoundInvalidCharacter
        {
            get
            {
                return ResourceManager.GetString("FoundInvalidCharacter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The ignore condition &apos;JsonIgnoreCondition.WhenWritingNull&apos; is not valid on value-type member &apos;{0}&apos; on type &apos;{1}&apos;. Consider using &apos;JsonIgnoreCondition.WhenWritingDefault&apos;..
        /// </summary>
        public static string IgnoreConditionOnValueTypeInvalid
        {
            get
            {
                return ResourceManager.GetString("IgnoreConditionOnValueTypeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot get the value of a token type &apos;{0}&apos; as a {1}..
        /// </summary>
        public static string InvalidCast
        {
            get
            {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid escapable character within a JSON string. The string should be correctly escaped..
        /// </summary>
        public static string InvalidCharacterAfterEscapeWithinString
        {
            get
            {
                return ResourceManager.GetString("InvalidCharacterAfterEscapeWithinString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid after &apos;/&apos; at the beginning of the comment. Expected either &apos;/&apos; or &apos;*&apos;..
        /// </summary>
        public static string InvalidCharacterAtStartOfComment
        {
            get
            {
                return ResourceManager.GetString("InvalidCharacterAtStartOfComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid within a JSON string. The string should be correctly escaped..
        /// </summary>
        public static string InvalidCharacterWithinString
        {
            get
            {
                return ResourceManager.GetString("InvalidCharacterWithinString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot compare the value of a token type &apos;{0}&apos; to text..
        /// </summary>
        public static string InvalidComparison
        {
            get
            {
                return ResourceManager.GetString("InvalidComparison", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The DuplicatePropertyNameHandling enum must be set to one of the supported values..
        /// </summary>
        public static string InvalidDuplicatePropertyNameHandling
        {
            get
            {
                return ResourceManager.GetString("InvalidDuplicatePropertyNameHandling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid token type for the end of the JSON payload. Expected either &apos;EndArray&apos; or &apos;EndObject&apos;..
        /// </summary>
        public static string InvalidEndOfJsonNonPrimitive
        {
            get
            {
                return ResourceManager.GetString("InvalidEndOfJsonNonPrimitive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a hex digit following &apos;\u&apos; within a JSON string. The string should be correctly escaped..
        /// </summary>
        public static string InvalidHexCharacterWithinString
        {
            get
            {
                return ResourceManager.GetString("InvalidHexCharacterWithinString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid leading zero before &apos;{0}&apos;..
        /// </summary>
        public static string InvalidLeadingZeroInNumber
        {
            get
            {
                return ResourceManager.GetString("InvalidLeadingZeroInNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments cannot be stored in a JsonDocument, only the Skip and Disallow comment handling modes are supported..
        /// </summary>
        public static string JsonDocumentDoesNotSupportComments
        {
            get
            {
                return ResourceManager.GetString("JsonDocumentDoesNotSupportComments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested operation requires an element of type &apos;{0}&apos;, but the target element has type &apos;{1}&apos;..
        /// </summary>
        public static string JsonElementHasWrongType
        {
            get
            {
                return ResourceManager.GetString("JsonElementHasWrongType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The non-public property &apos;{0}&apos; on type &apos;{1}&apos; is annotated with &apos;JsonIncludeAttribute&apos; which is invalid..
        /// </summary>
        public static string JsonIncludeOnNonPublicInvalid
        {
            get
            {
                return ResourceManager.GetString("JsonIncludeOnNonPublicInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property with name &apos;{0}&apos; already exists..
        /// </summary>
        public static string JsonObjectDuplicateKey
        {
            get
            {
                return ResourceManager.GetString("JsonObjectDuplicateKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments cannot be stored when deserializing objects, only the Skip and Disallow comment handling modes are supported..
        /// </summary>
        public static string JsonSerializerDoesNotSupportComments
        {
            get
            {
                return ResourceManager.GetString("JsonSerializerDoesNotSupportComments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max depth must be positive..
        /// </summary>
        public static string MaxDepthMustBePositive
        {
            get
            {
                return ResourceManager.GetString("MaxDepthMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot parse a JSON object containing metadata properties like &apos;$id&apos; into an array or immutable collection type. Type &apos;{0}&apos;..
        /// </summary>
        public static string MetadataCannotParsePreservedObjectToImmutable
        {
            get
            {
                return ResourceManager.GetString("MetadataCannotParsePreservedObjectToImmutable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;$id&apos; metadata property &apos;{0}&apos; conflicts with an existing identifier..
        /// </summary>
        public static string MetadataDuplicateIdFound
        {
            get
            {
                return ResourceManager.GetString("MetadataDuplicateIdFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The metadata property &apos;$id&apos; must be the first property in the JSON object..
        /// </summary>
        public static string MetadataIdIsNotFirstProperty
        {
            get
            {
                return ResourceManager.GetString("MetadataIdIsNotFirstProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties that start with &apos;$&apos; are not allowed on preserve mode, either escape the character or turn off preserve references by setting ReferenceHandler to null..
        /// </summary>
        public static string MetadataInvalidPropertyWithLeadingDollarSign
        {
            get
            {
                return ResourceManager.GetString("MetadataInvalidPropertyWithLeadingDollarSign", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid reference to value type &apos;{0}&apos;..
        /// </summary>
        public static string MetadataInvalidReferenceToValueType
        {
            get
            {
                return ResourceManager.GetString("MetadataInvalidReferenceToValueType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;$values&apos; metadata property must be a JSON array. Current token type is &apos;{0}&apos;..
        /// </summary>
        public static string MetadataInvalidTokenAfterValues
        {
            get
            {
                return ResourceManager.GetString("MetadataInvalidTokenAfterValues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deserialization failed for one of these reasons:
        ///1. {0}
        ///2. {1}.
        /// </summary>
        public static string MetadataPreservedArrayFailed
        {
            get
            {
                return ResourceManager.GetString("MetadataPreservedArrayFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid property &apos;{0}&apos; found within a JSON object that must only contain metadata properties and the nested JSON array to be preserved..
        /// </summary>
        public static string MetadataPreservedArrayInvalidProperty
        {
            get
            {
                return ResourceManager.GetString("MetadataPreservedArrayInvalidProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One or more metadata properties, such as &apos;$id&apos; and &apos;$values&apos;, were not found within a JSON object that must only contain metadata properties and the nested JSON array to be preserved..
        /// </summary>
        public static string MetadataPreservedArrayPropertyNotFound
        {
            get
            {
                return ResourceManager.GetString("MetadataPreservedArrayPropertyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A JSON object that contains a &apos;$ref&apos; metadata property must not contain any other properties..
        /// </summary>
        public static string MetadataReferenceCannotContainOtherProperties
        {
            get
            {
                return ResourceManager.GetString("MetadataReferenceCannotContainOtherProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference &apos;{0}&apos; not found..
        /// </summary>
        public static string MetadataReferenceNotFound
        {
            get
            {
                return ResourceManager.GetString("MetadataReferenceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;$id&apos; and &apos;$ref&apos; metadata properties must be JSON strings. Current token type is &apos;{0}&apos;..
        /// </summary>
        public static string MetadataValueWasNotString
        {
            get
            {
                return ResourceManager.GetString("MetadataValueWasNotString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid without a matching open..
        /// </summary>
        public static string MismatchedObjectArray
        {
            get
            {
                return ResourceManager.GetString("MismatchedObjectArray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members &apos;{0}&apos; and &apos;{1}&apos; on type &apos;{2}&apos; cannot both bind with parameter &apos;{3}&apos; in constructor &apos;{4}&apos; on deserialization..
        /// </summary>
        public static string MultipleMembersBindWithConstructorParameter
        {
            get
            {
                return ResourceManager.GetString("MultipleMembersBindWithConstructorParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The naming policy &apos;{0}&apos; cannot return null..
        /// </summary>
        public static string NamingPolicyReturnNull
        {
            get
            {
                return ResourceManager.GetString("NamingPolicyReturnNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is not enough data to read through the entire JSON array or object..
        /// </summary>
        public static string NotEnoughData
        {
            get
            {
                return ResourceManager.GetString("NotEnoughData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This JsonElement instance was not built from a JsonNode and is immutable..
        /// </summary>
        public static string NotNodeJsonElementParent
        {
            get
            {
                return ResourceManager.GetString("NotNodeJsonElementParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The maximum configured depth of {0} has been exceeded. Cannot read next JSON object..
        /// </summary>
        public static string ObjectDepthTooLarge
        {
            get
            {
                return ResourceManager.GetString("ObjectDepthTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference metadata is not honored when deserializing types using parameterized constructors. See type &apos;{0}&apos;..
        /// </summary>
        public static string ObjectWithParameterizedCtorRefMetadataNotHonored
        {
            get
            {
                return ResourceManager.GetString("ObjectWithParameterizedCtorRefMetadataNotHonored", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON property name of length {0} is too large and not supported..
        /// </summary>
        public static string PropertyNameTooLarge
        {
            get
            {
                return ResourceManager.GetString("PropertyNameTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property with name &apos;{0}&apos; not found..
        /// </summary>
        public static string PropertyNotFound
        {
            get
            {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property with name &apos;{0}&apos; has a different type than expected..
        /// </summary>
        public static string PropertyTypeMismatch
        {
            get
            {
                return ResourceManager.GetString("PropertyTypeMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid within a number, immediately after a decimal point (&apos;.&apos;). Expected a digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string RequiredDigitNotFoundAfterDecimal
        {
            get
            {
                return ResourceManager.GetString("RequiredDigitNotFoundAfterDecimal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid within a number, immediately after a sign character (&apos;+&apos; or &apos;-&apos;). Expected a digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string RequiredDigitNotFoundAfterSign
        {
            get
            {
                return ResourceManager.GetString("RequiredDigitNotFoundAfterSign", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a digit (&apos;0&apos;-&apos;9&apos;), but instead reached end of data..
        /// </summary>
        public static string RequiredDigitNotFoundEndOfData
        {
            get
            {
                return ResourceManager.GetString("RequiredDigitNotFoundEndOfData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The converter &apos;{0}&apos; is not compatible with the type &apos;{1}&apos;..
        /// </summary>
        public static string SerializationConverterNotCompatible
        {
            get
            {
                return ResourceManager.GetString("SerializationConverterNotCompatible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The converter specified on &apos;{0}&apos; does not derive from JsonConverter or have a public parameterless constructor..
        /// </summary>
        public static string SerializationConverterOnAttributeInvalid
        {
            get
            {
                return ResourceManager.GetString("SerializationConverterOnAttributeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The converter specified on &apos;{0}&apos; is not compatible with the type &apos;{1}&apos;..
        /// </summary>
        public static string SerializationConverterOnAttributeNotCompatible
        {
            get
            {
                return ResourceManager.GetString("SerializationConverterOnAttributeNotCompatible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The converter &apos;{0}&apos; read too much or not enough..
        /// </summary>
        public static string SerializationConverterRead
        {
            get
            {
                return ResourceManager.GetString("SerializationConverterRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The converter &apos;{0}&apos; wrote too much or not enough..
        /// </summary>
        public static string SerializationConverterWrite
        {
            get
            {
                return ResourceManager.GetString("SerializationConverterWrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The data extension property &apos;{0}.{1}&apos; does not match the required signature of IDictionary&lt;string, JsonElement&gt; or IDictionary&lt;string, object&gt;..
        /// </summary>
        public static string SerializationDataExtensionPropertyInvalid
        {
            get
            {
                return ResourceManager.GetString("SerializationDataExtensionPropertyInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; cannot exist more than once on &apos;{1}&apos;..
        /// </summary>
        public static string SerializationDuplicateAttribute
        {
            get
            {
                return ResourceManager.GetString("SerializationDuplicateAttribute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot have more than one property that has the attribute &apos;{1}&apos;..
        /// </summary>
        public static string SerializationDuplicateTypeAttribute
        {
            get
            {
                return ResourceManager.GetString("SerializationDuplicateTypeAttribute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than zero..
        /// </summary>
        public static string SerializationInvalidBufferSize
        {
            get
            {
                return ResourceManager.GetString("SerializationInvalidBufferSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The unsupported member type is located on type &apos;{0}&apos;..
        /// </summary>
        public static string SerializationNotSupportedParentType
        {
            get
            {
                return ResourceManager.GetString("SerializationNotSupportedParentType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string SerializationNotSupportedType
        {
            get
            {
                return ResourceManager.GetString("SerializationNotSupportedType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The converter &apos;{0}&apos; cannot return a null value..
        /// </summary>
        public static string SerializerConverterFactoryReturnsNull
        {
            get
            {
                return ResourceManager.GetString("SerializerConverterFactoryReturnsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of {0}. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles..
        /// </summary>
        public static string SerializerCycleDetected
        {
            get
            {
                return ResourceManager.GetString("SerializerCycleDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Serializer options cannot be changed once serialization or deserialization has occurred..
        /// </summary>
        public static string SerializerOptionsImmutable
        {
            get
            {
                return ResourceManager.GetString("SerializerOptionsImmutable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON property name for &apos;{0}.{1}&apos; collides with another property..
        /// </summary>
        public static string SerializerPropertyNameConflict
        {
            get
            {
                return ResourceManager.GetString("SerializerPropertyNameConflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON property name for &apos;{0}.{1}&apos; cannot be null..
        /// </summary>
        public static string SerializerPropertyNameNull
        {
            get
            {
                return ResourceManager.GetString("SerializerPropertyNameNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Serialization and deserialization of &apos;System.Type&apos; instances are not supported and should be avoided since they can lead to security issues..
        /// </summary>
        public static string SerializeTypeInstanceNotSupported
        {
            get
            {
                return ResourceManager.GetString("SerializeTypeInstanceNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The object or value could not be serialized..
        /// </summary>
        public static string SerializeUnableToSerialize
        {
            get
            {
                return ResourceManager.GetString("SerializeUnableToSerialize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .NET number values such as positive and negative infinity cannot be written as valid JSON..
        /// </summary>
        public static string SpecialNumberValuesNotSupported
        {
            get
            {
                return ResourceManager.GetString("SpecialNumberValuesNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stream is not writable..
        /// </summary>
        public static string StreamNotWritable
        {
            get
            {
                return ResourceManager.GetString("StreamNotWritable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON array contains a trailing comma at the end which is not supported in this mode. Change the reader options..
        /// </summary>
        public static string TrailingCommaNotAllowedBeforeArrayEnd
        {
            get
            {
                return ResourceManager.GetString("TrailingCommaNotAllowedBeforeArrayEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a trailing comma at the end which is not supported in this mode. Change the reader options..
        /// </summary>
        public static string TrailingCommaNotAllowedBeforeObjectEnd
        {
            get
            {
                return ResourceManager.GetString("TrailingCommaNotAllowedBeforeObjectEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of data while reading a comment..
        /// </summary>
        public static string UnexpectedEndOfDataWhileReadingComment
        {
            get
            {
                return ResourceManager.GetString("UnexpectedEndOfDataWhileReadingComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found invalid line or paragraph separator character while reading a comment..
        /// </summary>
        public static string UnexpectedEndOfLineSeparator
        {
            get
            {
                return ResourceManager.GetString("UnexpectedEndOfLineSeparator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON value of length {0} is too large and not supported..
        /// </summary>
        public static string ValueTooLarge
        {
            get
            {
                return ResourceManager.GetString("ValueTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed..
        /// </summary>
        public static string ZeroDepthAtEnd
        {
            get
            {
                return ResourceManager.GetString("ZeroDepthAtEnd", resourceCulture);
            }
        }
    }
}
